version: '3.9'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 vopetschool.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=vopetschool.settings
      - POSTGRES_DB=vopetschool
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - DJANGO_SETTINGS_MODULE=vopetschool.settings

    environment:
      POSTGRES_DB: vopetschool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
