# Generated by Django 5.2.3 on 2025-07-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_alter_comment_options_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
