# Generated by Django 5.2.3 on 2025-07-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0006_petitionreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('pending', 'Очікує на розгляд'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], default='new', max_length=10),
        ),
    ]
