# Generated by Django 5.2.3 on 2025-07-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0007_petition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionreview',
            name='petition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='petitions.petition'),
        ),
    ]
