# Generated by Django 5.2.4 on 2025-07-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0009_petition_reviewed_at_petition_reviewed_by_and_more'),
        ('schoolgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolgroups.classgroup'),
        ),
    ]
