# Generated by Django 5.2.4 on 2025-07-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_student_school_class_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='students',
        ),
        migrations.RemoveField(
            model_name='teachergroup',
            name='teachers',
        ),
    ]
