# Generated by Django 5.2.3 on 2025-07-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
