# Generated by Django 5.2.3 on 2025-07-05 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote_class_groups_vote_teacher_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteanswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_options', to='voting.voteoption'),
        ),
    ]
