# Generated by Django 5.2.4 on 2025-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolgroups', '0001_initial'),
        ('voting', '0006_alter_voteanswer_option_alter_voteanswer_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='class_groups',
            field=models.ManyToManyField(blank=True, to='schoolgroups.classgroup'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='teacher_groups',
            field=models.ManyToManyField(blank=True, to='schoolgroups.teachergroup'),
        ),
    ]
