# Generated by Django 5.2.3 on 2025-07-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_classgroup_class_names_classgroup_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_groups', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='teachergroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='groups', to='accounts.teacher'),
        ),
    ]
