# Generated by Django 5.2.4 on 2025-07-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_classgroup_students_and_more'),
        ('petitions', '0010_alter_petition_class_group'),
        ('voting', '0007_alter_vote_class_groups_alter_vote_teacher_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassGroup',
        ),
        migrations.DeleteModel(
            name='TeacherGroup',
        ),
    ]
