# Generated by Django 5.2.4 on 2025-07-07 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created_petition', 'Created Petition'), ('supported_petition', 'Supported Petition'), ('created_vote', 'Created Vote'), ('answered_vote', 'Answered Vote')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_object_title', models.CharField(max_length=255)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_info', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
