# Generated by Django 5.2.3 on 2025-07-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_classgroup_teachergroup'),
        ('voting', '0002_alter_vote_end_date_alter_vote_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='class_groups',
            field=models.ManyToManyField(blank=True, to='accounts.classgroup'),
        ),
        migrations.AddField(
            model_name='vote',
            name='teacher_groups',
            field=models.ManyToManyField(blank=True, to='accounts.teachergroup'),
        ),
    ]
