# Generated by Django 5.2.3 on 2025-07-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voteanswer_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteanswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_answers', to='voting.voteoption'),
        ),
    ]
